#set( EXTRA_FLAGS "/Oi /Zm250 /D_CRT_SECURE_NO_WARNINGS" )

#set( CMAKE_CXX_FLAGS_DEBUG_INIT          "/MDd /Od /Ob0 /D_DEBUG /Zi /RTC1   ${EXTRA_FLAGS}" )
#set( CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "/MD  /O1 /Ob1 /DNDEBUG             ${EXTRA_FLAGS}" )
#set( CMAKE_CXX_FLAGS_RELEASE_INIT        "/MD  /O2 /Ob2 /DNDEBUG /Zi /arch:SSE2  ${EXTRA_FLAGS}" )
#set( CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/MD  /O2 /Ob1 /DNDEBUG /Zi         ${EXTRA_FLAGS}" )

#set( CMAKE_EXE_LINKER_FLAGS_RELEASE "/debug /INCREMENTAL:NO" )
